# Generated by Django 3.2.4 on 2022-06-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
        ('interviews', '0007_auto_20220224_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone_call', 'Phone call'), ('assessment_real_time', 'Assessment Real Time'), ('assessment_submit', 'Assessment Submit'), ('video_call', 'Video Call'), ('onsite_interview', 'Onsite Interview'), ('not_mentioned', 'Not mentioned')], max_length=50, verbose_name='Type'),
        ),
    ]
