# Generated by Django 4.0.4 on 2022-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_auto_20220616_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='round',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Round'),
        ),
    ]
