# Generated by Django 3.2.1 on 2022-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_interview_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduling', 'Scheduling'), ('scheduled', 'Scheduled'), ('working', 'Working'), ('done', 'Done and Waiting for the Result'), ('sent_reminder', 'Sent Reminder'), ('canceled', 'Canceled Interview by Company'), ('missed', 'Missed Interview by Student'), ('got_other_offer', 'No need to Attend due to another offer'), ('pause_application', 'No need to Attend due to paused applications'), ('rejected', 'Rejected'), ('passed', 'Passed'), ('offered', 'Offered'), ('deleted', 'Deleted')], max_length=50, verbose_name='Status'),
        ),
    ]
