# Generated by Django 3.2.1 on 2022-06-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
        ('applications', '0004_alter_application_job_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to='users.user'),
        ),
    ]
