# Generated by Django 3.2.1 on 2022-07-01 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
        ('applications', '0006_auto_20220628_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_updated_by', to='users.user'),
        ),
    ]
