# Generated by Django 3.2.4 on 2022-08-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='student',
            new_name='student_id',
        ),
    ]
