# Generated by Django 3.2.4 on 2022-08-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0002_rename_student_studentstatus_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='student_id',
            new_name='student',
        ),
    ]
