# Generated by Django 3.2.4 on 2022-08-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0005_alter_studentstatus_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='created_by',
            new_name='updated_by',
        ),
    ]
