# Generated by Django 3.2.4 on 2022-08-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_alter_student_student_id'),
        ('student_statuses', '0008_auto_20220812_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='student_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='student_name'),
            preserve_default=False,
        ),
    ]
