# Generated by Django 3.2.4 on 2022-08-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0009_studentstatus_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='name',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='student_name',
        ),
    ]
