# Generated by Django 3.2.4 on 2022-08-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0011_studentstatus_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='student_name',
            new_name='name',
        ),
    ]
