# Generated by Django 3.2.4 on 2022-08-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0013_alter_studentstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
