# Generated by Django 3.2.7 on 2022-08-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0015_alter_studentstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='student_history_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Student ID'),
        ),
    ]
