# Generated by Django 3.2.7 on 2022-08-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0017_alter_studentstatus_student_history_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='student_history_id',
            new_name='history_student_id',
        ),
    ]
