# Generated by Django 3.2.7 on 2022-08-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_statuses', '0018_rename_student_history_id_studentstatus_history_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='history_student_id',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Student ID'),
        ),
    ]
