# Generated by Django 3.2.1 on 2022-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
