# Generated by Django 3.2.1 on 2022-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='github_status',
            field=models.CharField(choices=[('not_started', 'Not Started Creating'), ('on_progress', 'On Progress'), ('done', 'Done by Developer Team'), ('reviewed', 'Reviewed by Job Support'), ('req_modification', 'Required Modification')], default='not_started', max_length=50, verbose_name='Github Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='portfolio_status',
            field=models.CharField(choices=[('not_started', 'Not Started Creating'), ('on_progress', 'On Progress'), ('done', 'Done by Developer Team'), ('reviewed', 'Reviewed by Job Support'), ('req_modification', 'Required Modification')], default='not_started', max_length=50, verbose_name='Portfolio Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume_status',
            field=models.CharField(choices=[('not_started', 'Not Started Creating'), ('on_progress', 'On Progress'), ('done', 'Done by Developer Team'), ('reviewed', 'Reviewed by Job Support'), ('req_modification', 'Required Modification')], default='not_started', max_length=50, verbose_name='Resume Status'),
        ),
    ]
