# Generated by Django 3.2.7 on 2022-07-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_partner_application_explanation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('graduated', 'Graduated'), ('preparing', 'Preaparing'), ('perpared_by_dev_team', 'Prepared by Developer Team'), ('started_application', 'Started Application'), ('pause_application', 'Pause Application'), ('got_offer', 'Got an Offer'), ('joined', 'Joined'), ('activated_payment', 'Activated Payment'), ('failed', 'Failed to Get a Job'), ('deleted', 'Deleted'), ('reapply', 'Reapply'), ('missing', 'Missing')], db_index=True, max_length=20, verbose_name='Status'),
        ),
    ]
