# Generated by Django 3.2.4 on 2022-08-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=None, max_length=100, unique=True, verbose_name='Student ID'),
        ),
    ]
