# Generated by Django 3.2.7 on 2022-08-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=50, verbose_name='Student ID'),
        ),
    ]
